[package]
name = "litec_parse"
version = "0.1.0"
edition = "2024"

[dependencies]
litec_ast = { path = "../litec_ast" }
litec_error = { path = "../litec_error" }
litec_span = { path = "../litec_span" }
litec_session = { path = "../litec_session" }
unicode-ident = { workspace = true }
unicode-width = { workspace = true }

[dev-dependencies]
expect-test = "1.5.1"
